### PR TITLE
add gene expression benchmark notebook

### PR DESCRIPTION
**Pull request by lkeegan**
- implements the gene expression model A.6 from https://link.springer.com/978-3-319-63113-4
- benchmarks runtime of direct and rssa solvers for this model
- checks correctness of solvers for simplified model with analytic solution

### CODE REVIEW

**Comment by tristan0x** [comment]
This is very nice work. Thank you. To prevent messing with the user_manual, could you please move your notebook to a new directory named  `/notebooks`

**Comment by tristan0x** [comment]
Furthermore, could you please fix trivial formatting issues with `clean_ipynb` utility, using this [PR](https://github.com/KwatME/clean_ipynb/pull/3)
(You will also have to install `isort` Python packages manually to make it work.)

Usage: `clean_ipynb --black-opt -S benchmark_gene_expression.ipynb`

**Comment by tristan0x** [comment]
What about swapping axis of plots "%s vs analytic infinite volume"?

**Comment by tristan0x** [comment]
> Furthermore, could you please fix trivial formatting issues with `clean_ipynb` utility, using this [PR](https://github.com/KwatME/clean_ipynb/pull/3)
> (You will also have to install `isort` Python packages manually to make it work.)
> 
> Usage: `clean_ipynb --black-opt -S benchmark_gene_expression.ipynb`

my 2 PRs have been merged, and published to pypi. So `pip install -U clean_ipynb` is enough to install the proper version now.

**Comment by lkeegan** [comment]
moved to a new notebooks folder & formatted with clean_ipynb - this is a nice tool!
also added a notebook with some (hopefully correct) helper functions for converting units (thanks @jorblancoa and @iomaganaris!)
> What about swapping axis of plots "%s vs analytic infinite volume"?
these plots are showing counts as a function of the time in the simulation, so I think swapping the axes will be confusing, e.g. when you plot a function f(t) typically you choose t for the x-axis and the f(t) for the y-axis

**Pull request closed without merging**
