### PR TITLE
Updated rallpack3.py

### PR DESCRIPTION
**Pull request by iahepburn**
Question about what to do with other (bigger, slower) models - modernise for STEPS 3.5+ or keep them in their published state.

### CODE REVIEW

**Comment by WeiliangChenOIST** [comment]
Do you mean the ones in https://github.com/CNS-OIST/STEPS_Example/tree/master/publication_models? I think minimally we need to keep the original publication copy, then if someone has time an up-to-date version can also be provided as well.

**Comment by iahepburn** [comment]
I do mean those, yeah. I updated one (rallpack3) with a simple indexing fix, but the other models would take a lot longer to check I would think.

**Comment by WeiliangChenOIST** [comment]
The fix doesn't work with the published version of STEPS though. maybe provide multiple versions of the scripts and label them with the matching STEPS versions e.g. `rallpack3_original.py` and `rallpack3_steps3.6.0.py`

**Comment by iahepburn** [comment]
it doesn't work with 3.5??

**Comment by WeiliangChenOIST** [comment]
There is no `UNKNOWN_TET` defined pre 3.5. The scripts in https://github.com/CNS-OIST/STEPS_Example/tree/master/publication_models were kept as they were in publication.

**Comment by iahepburn** [comment]
Rallpack1 was already updated similarly as to this PR.

**Comment by iahepburn** [comment]
I.e https://github.com/CNS-OIST/STEPS_Example/blob/efbe75862c3668412f4b7a43a8345cc6814f870a/publication_models/API_1/Hepburn_FComNeuroSic_2013/rallpack1.py#L101

**Comment by WeiliangChenOIST** [comment]
indeed looks like it was...To make them runnable with older STEPS may be it is better to add the following as well

```
try:   
    from steps.geom import UNKNOWN_TET
except ImportError:
    UNKNOWN_TET = -1
```

**Comment by iahepburn** [comment]
we might open up a can of worms trying to make scripts run on different versions. I think our original idea was to specify which scripts worked on different versions (and add versions as we released new versions of STEPS). I think this is a good idea, but I can see it being one of those things that keeps getting put off.

**Comment by iahepburn** [comment]
anyway, both rallpack1 and 3 work fine with STEPS 3.6, but not sure now what to do with this PR. I don't have time to reorganise everything right now.

**Comment by WeiliangChenOIST** [comment]
We can just keep the updated version if we like, there shouldn't be many people try to run them with old steps anyway. What we need to do is to provide a text at the beginning of the script mentioning the STEPS version that has been tested for the script.

**Review by WeiliangChenOIST — APPROVED** [review]

**Pull request merged**
